bizwallet/blog/urls.py
from django.urls import path

from .views import PostDetail, PostList, SearchPostList, post_share, tag_posts

app_name = "blogs"
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('search/', SearchPostList.as_view(), name="search"),
    path('<slug>/', PostDetail, name='detail'),
    path('<slug>/share/', post_share, name='share'),
    path('tag/<slug:tag_slug>/', tag_posts, name='posts_by_tag'),
]

bizwallet/core/urls.py
from django.urls import path

from bizwallet.core.views import email_subscribe, service_detail

app_name = "services"
urlpatterns = [
    path("<int:pk>/", view=service_detail, name="detail"),
    path("subscribe/", view=email_subscribe, name="subscribe"),
]

bizwallet/users/urls.py
from django.urls import path, re_path

from bizwallet.users.views import (  # subscribe_view,
    BankUpdateView,
    NotificationView,
    TopWalletViews,
    UpdatePhotoView,
    WithdrawalView,
    call_back_url,
    kin_creation,
    subscribe,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~dp-update/", view=UpdatePhotoView.as_view(), name="photo"),
    path("~bank-update/", view=BankUpdateView.as_view(), name="bank"),
    path("~add-kin/", view=kin_creation, name="kin"),
    path("~top-up/", view=TopWalletViews.as_view(), name="topup"),
    path("~withdraw/", view=WithdrawalView.as_view(), name="withdraw"),
    path("~subscribe/", view=subscribe, name="subscribe"),
    path("~notification/", view=NotificationView.as_view(), name="notif"),
    re_path("~payment/$", view=call_back_url, name="payment"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from __future__ import absolute_import

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from filebrowser.sites import site

from bizwallet.core.views import contact_view, home
from bizwallet.users.views import fieldworker_signup, investor_signup
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", home, name="home"),
    path("usersref=/<username>/", home, name="ref-home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "about/services/", TemplateView.as_view(template_name="pages/services.html"), name="services"
    ),
    path(
        "about/president/ayo-ogungbe/", TemplateView.as_view(template_name="pages/ceo.html"), name="ceo"
    ),
    path(
        "services/", include("bizwallet.core.urls"), name="services"
    ),
    path(
        "contact/", contact_view, name="contact"
    ),
    path("news/", include("bizwallet.blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# User URIs
urlpatterns += [
    # User management
    # Custom users registration
    path(
        "accounts/select/", TemplateView.as_view(template_name="account/signup_select.html"), name="account_select"
    ),
    path("accounts/signup/", investor_signup, name="account_signup"),
    path("accounts/signup-fieldworker/", fieldworker_signup, name="worker_signup"),
    path("users/", include("bizwallet.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
]

# Admin urls and security
urlpatterns += [
    # Django Admin, use {% url 'admin:index' %}
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("jet/", include("jet.urls", namespace="jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", namespace="jet-dashboard")),
    path("flatpage/", include("django.contrib.flatpages.urls")),
    path(settings.ADMIN_FILEBROWSER_URL, site.urls),
    # path('grappelli/', include('grappelli.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),
]

# SEO url settings
urlpatterns += [
    # Your stuff: custom urls includes go here
    path("sitemap.xml/", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
    path("tinymce/", include("tinymce.urls")),
    # Cookie consent
    # path('cookies/', include('cookie_consent.urls')),
    # Language switcher support urls for django
    path("i18n/", include("django.conf.urls.i18n")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # # DRF auth token
    # path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bizwallet/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField(required=True)
    to = forms.EmailField(required=True)
    comments = forms.CharField(required=False, widget=forms.Textarea)

bizwallet/blog/views.py
try:
    from urllib import quote_plus  # python 2
except:
    pass

try:
    from urllib.parse import quote_plus  # python 3
except:
    pass

import datetime

from category.models import Tag
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import transaction
from django.db.models import Count, F, Q, Sum
from django.http import HttpResponseForbidden, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, FormMixin, UpdateView

from .forms import EmailPostForm
from .models import Post  # , Comment

User = get_user_model()

# Create your views here.
class PostList(ListView):
    model = Post
    template_name = "blog/list.html"
    ordering = ["title", "-pub_date"]
    queryset = Post.objects.all_posts()
    context_object_name = "posts"
    allow_empty = True
    paginate_by = 5
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all()
        recent_posts = Post.objects.recent_posts()[:5]
        context["tags"] = tags
        context["recent_posts"] = recent_posts
        return context


class SearchPostList(ListView):
    model = Post
    template_name = "blog/search_list.html"
    ordering = ["title", "-pub_date"]
    context_object_name = "posts"
    allow_empty = True
    paginate_by = 5
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        return Post.objects.filter(
            Q(title__icontains=query) | 
            Q(content__icontains=query)
        ).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all()
        recent_posts = Post.objects.recent_posts()[:5]
        context["tags"] = tags
        context["recent_posts"] = recent_posts
        return context



def tag_posts(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag], status="published")
        print("tag object id = ", object_list)

    tags = Tag.objects.all()
    recent_posts = Post.objects.recent_posts()[:5]

    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    data = {
        'page': page,
        'posts': posts,
        'tags': tags,
        'recent_posts': recent_posts,
        'tag': tag
    }        
    return render(request, 'blog/tags.html', data)




def post_share(request, slug):
    post = get_object_or_404(Post, slug=slug, status="published")
    if not request.method == "POST":
        HttpResponseForbidden

    tags = Tag.objects.all()
    recent_posts = Post.objects.recent_posts()[:5]

    form = EmailPostForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        post_url = request.build_absolute_url(post.get_absolute_url())
        subject = f"{cd['name']} recommends you read {post.title}"
        message = f"Read {post.title} at {post_url} \n\n {cd['name']}\'s comments: {cd['comments']}"
        send_mail(
            subject,
            message,
            "info@bizwallet.com",
            [cd['to']],
            fail_silently=False
        )
        messages.success(request, f"You have successfully shared {post.title}")
        return HttpResponseRedirect(reverse_lazy('blogs:list'))
    else:
        form = EmailPostForm()

    data = {
        'tags': tags,
        'recent_posts': recent_posts,
        'post': post, 
        'form': form
    }
    
    return render(request, 'blog/share.html', data)




def PostDetail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    tags = Tag.objects.all()
    recent_posts = Post.objects.recent_posts().exclude(id=post.id)[:5]
    post_tags_ids = post.tags.values_list('id', flat=True)
    related_posts = Post.objects.all_posts().filter(tags__in=post_tags_ids).exclude(id=post.id)
    related_posts = related_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-pub_date')[:5]




    data = {
        "post": post,
        'recent_posts': recent_posts,
        'related_posts': related_posts,
        "tags": tags
    }
    return render(request, "blog/detail.html", data)

bizwallet/core/views.py
from __future__ import absolute_import

import json
import os

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import BadHeaderError, EmailMessage, send_mail, send_mass_mail
from django.http import Http404, HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from tinymce.views import render_to_image_list

from bizwallet.users.forms import TestimonyForm
from bizwallet.users.models import Testimonial

from .forms import ContactForm, EmailSubscribeForm
from .models import EmailSubscribe, Services

User = get_user_model()

devnull = open(os.devnull, "w")


def compress_whitespace(s):
    return " ".join(s.split())

def get_ip_address(request):
    """ use requestobject to fetch client machine's IP Address """
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', None)
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR', None)    ### Real IP address of client Machine
    return ip  

@cache_page(60 * 10)  # cached in 1 second.. for 15 minutes (60 sec x 15mins)
@csrf_protect
def home(request, *args, **kwargs):
    # get referrer linked to reffered using username
    username = str(kwargs.get("username"))

    ip_address = get_ip_address(request)
    print(ip_address)

   
    services = Services.objects.all().filter(active=True)
    testimonials = Testimonial.objects.filter(active=True).order_by("-created")[:5]

    try:
        user = User.objects.get(username=username)
        if user.is_field_worker:
            request.session["fieldworker_id"] = user.id
            user_ip = request.session["fieldworker_id"]
    except:
        pass



    try:
        is_cached = "geodata" in request.session
        # get user ip and get information of the user
        if not is_cached:
            response = requests.get(f"https://reallyfreegeoip.org/json/{ip_address}")
            request.session["geodata"] = response.json()

        geodata = request.session["geodata"]
        print(geodata)
        request.session["user_ip"] = geodata["ip"]
        request.session["country"] = geodata["country_name"]
        print(request.session.get("country"))
        request.session["country_code"] = geodata["country_code"]
        request.session["region_name"] = geodata["region_name"]
        request.session["city"] = geodata["city"]
    except:
        pass

    if not request.session.get("user_ip"):
        messages.info(
            request,
            _(
                "Welcome to Bizwallet Co-Operative. Please feel free to communicate any challanges with the support team."
            ),
        )

    if request.method == 'POST':
        form = TestimonyForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('home'))
            messages.success(request, "Your review has been submitted successfuly")
            send_mail("New Testimonial Submitted", "Some Just submitted a new testimonial", "no-reply@bizwallet.org", ['info@bizwallet.org'], fail_silently=False)
    else:
        form = TestimonyForm()

    return render(request, "pages/home.html", {"form":form, "is_cached": is_cached, "services": services, "testimonials": testimonials})


class ServiceListView(DetailView):
    model = Services
    template_name = 'pages/services.html'
    context_object_name = 'services'
    queryset = Services.objects.filter(active=True)

    def get_object(self, queryset=None):
        return Services.objects.get(pk=self.kwargs.get("pk"))

service_detail = ServiceListView.as_view()


def contact_view(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            html_message = render_to_string('email/support_mail.html', {'message': message, 'from_email': from_email, 'subject': subject})

            try:
                send_mail(subject, message, from_email, ['info@bizwallet.org'], html_message=html_message, fail_silently=False)
                messages.success(request, "Your Email Has been sent successfuly")
            except BadHeaderError:
                messages.error(request, "There was an error sending yout email at the moment, please try again later.")
                # return HttpResponse('Invalid Header found')
            return redirect('home')
    return render(request, 'pages/contact.html', {'form': form})



class UserEmailSubscribe(SuccessMessageMixin, CreateView):

    model = EmailSubscribe
    template_name = "snippets/footer.html"
    form_class = EmailSubscribeForm
    success_url = reverse_lazy("home")
    success_message = _("Email successfully added to our email list")

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())

email_subscribe = UserEmailSubscribe.as_view()

bizwallet/templates/users/notification.html
{% extends "base_dashboard.html" %}
{% load crispy_forms_tags static %}

{% block title %}Notification Settings - {{ user.username }} | {{ block.super }}{% endblock %}

{% block header %}
<!-- Header -->
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
  style="min-height: 600px; background-image: url({% static 'images/profile-cover.jpg' %}); background-size: cover; background-position: center top;">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-12 col-md-10">
        <h1 class="display-2 text-white">Hello {{request.user.fullname}}</h1>
        <p class="text-white mt-0 mb-5">Here you enable your notifcation for certain alerts. Ensure to ebanle these functions to allow us send you email notifcations based on latest happening and software changes.</p>
        <a href="{% url 'users:kin' %}" class="btn btn-info">Add Next of Kin</a>
      </div>
    </div>
  </div>
</div>
<!-- Page content -->

{% endblock header %}


{% block content %}
<div class="row">
    <div class="col-xl-4 order-2 mb-5 mb-xl-0 mt-5 mt-xl-0">
        <div class="card card-profile shadow">
            <div class="row justify-content-center">
                <div class="col-lg-3 order-lg-2">
                    <div class="card-profile-image">
                        <a href="{% url 'users:photo' %}">
                            <img
                            src="{% if request.user.image %}{{request.user.image.url}}{% else %}{% static 'images/user.png' %}{% endif %}"
                            class="rounded-circle">
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                {% if request.user.is_verified %}
                <div class="d-flex justify-content-between"  style="margin-bottom: 3.5rem;">
                    <a href="{% url 'users:topup' %}" class="btn btn-sm btn-info mr-4">Top Up Wallet</a>
                    <a href="{% url 'users:withdraw' %}" class="btn btn-sm btn-default float-right">Withdraw from wallet</a>
                </div>
                {% endif %}
            </div>
            <div class="card-body pt-0 pt-md-4">
                <div class="text-center mt-md-5">
                    <h3>
                        {{request.user.fullname}}<span class="font-weight-light">, {{request.user.age}}</span>
                    </h3>
                    <div class="h5 font-weight-300">
                        <i class="ni location_pin mr-2"></i>{{request.user.city}}, {{request.user.country}}
                    </div>
                    <div class="h5 mt-4">
                        <i class="ni business_briefcase-24 mr-2"></i>{{request.user.occupation}}
                        -{{request.user.company}}
                    </div>
                    <div>
                        <i class="ni education_hat mr-2"></i>{{request.user.office_address}}
                    </div>
                    <hr class="my-4" />
                    <div class="row">
                        <div class="col-12">
                            <div class="card-profile-stats">
                                <div>
                                    <span class="heading">{{request.user.userprofile.bank_name}}</span>
                                    <span class="description">Bank Name</span>
                                </div>
                                <div>
                                    <span class="heading">{{request.user.userprofile.account_number}}</span>
                                    <span class="description">Acc Number</span>
                                </div>
                                <div>
                                    <span class="heading">{{request.user.userprofile.bvn}}</span>
                                    <span class="description">BVN</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if not request.user.is_verified %}
                    <a href="{% url 'users:bank' %}" class="btn btn-primary btn-sm">Update Bank Details</a>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

    <div class="col-xl-8 order-1 mb-5 mb-xl-0">
        <div class="car bg-secondary shadow">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3>Update Your Alert settings</h3>
                    </div>
                    <div class="col-4 text-right">
                        <a href="{% url 'account_change_password' %}" class="btn btn-sm btn-primary">Update Password</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form enctype="multipart/form-data" method="post" action="{% url 'users:notif' %}">
                    <h6 class="heading-small text-muted mb-4">User allowed notifications</h6>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="button btn btn-primary">Enable Notifications</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bizwallet/templates/users/payment.html
{% extends "base_dashboard.html" %}
{% load crispy_forms_tags %}

{% block title %}Complete Payment for - {{ user.username }} | {{ block.super }}{% endblock %}


{% block content %}
{% endblock %}

bizwallet/templates/users/user_form.html
{% extends "base_dashboard.html" %}
{% load crispy_forms_tags static %}

{% block title %}{{ user.username }}{% endblock %}

{% block header %}
<!-- Header -->
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
  style="min-height: 600px; background-image: url({% static 'images/profile-cover.jpg' %}); background-size: cover; background-position: center top;">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white">Hello {{request.user.fullname}}</h1>
        <p class="text-white mt-0 mb-5">This is your profile page. You can see the basic informations you've attached
          with your account here
          and manage your projects or add a new next of kin</p>
        <a href="{% url 'users:kin' %}" class="btn btn-info">Add Next of Kin</a>
      </div>
    </div>
  </div>
</div>
<!-- Page content -->

{% endblock header %}


{% block content %}
<div class="row">
  <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
    <div class="card card-profile shadow">
      <div class="row justify-content-center">
        <div class="col-lg-3 order-lg-2">
          <div class="card-profile-image">
            <a href="{% url 'users:photo' %}">
              <img
                src="{% if request.user.image %}{{request.user.image.url}}{% else %}{% static 'images/user.png' %}{% endif %}"
                class="rounded-circle">
            </a>
          </div>
        </div>
      </div>
      <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        {% if request.user.is_verified %}
        <div class="d-flex justify-content-between"  style="margin-bottom: 3.5rem;">
          <a href="{% url 'users:topup' %}" class="btn btn-sm btn-info mr-4">Top Up Wallet</a>
          <a href="{% url 'users:withdraw' %}" class="btn btn-sm btn-default float-right">Withdraw from wallet</a>
        </div>
        {% endif %}
      </div>
      <div class="card-body pt-0 pt-md-4">
        <div class="text-center mt-md-5">
          <h3>
            {{request.user.fullname}}<span class="font-weight-light">, {{request.user.age}}</span>
          </h3>
          <div class="h5 font-weight-300">
            <i class="ni location_pin mr-2"></i>{{request.user.city}}, {{request.user.country}}
          </div>
          <div class="h5 mt-4">
            <i class="ni business_briefcase-24 mr-2"></i>{{request.user.occupation}} -{{request.user.company}}
          </div>
          <div>
            <i class="ni education_hat mr-2"></i>{{request.user.office_address}}
          </div>
          <hr class="my-4" />
          <div class="row">
            <div class="col-12">
              <div class="card-profile-stats">
                <div>
                  <span class="heading">{{request.user.userprofile.bank_name}}</span>
                  <span class="description">Bank Name</span>
                </div>
                <div>
                  <span class="heading">{{request.user.userprofile.account_number}}</span>
                  <span class="description">Acc Number</span>
                </div>
                <div>
                  <span class="heading">{{request.user.userprofile.bvn}}</span>
                  <span class="description">BVN</span>
                </div>
              </div>
            </div>
          </div>


          {% if not request.user.is_verified %}
          <a href="{% url 'users:bank' %}" class="btn btn-primary btn-sm">Update Bank Details</a>
          {% endif %}
        </div>
      </div>
    </div>

  </div>

  <div class="col-xl-8 order-xl-1">
    <div class="car bg-secondary shadow">
      <div class="card-header bg-white border-0">
        <div class="row align-items-center">
          <div class="col-8">
            <h3>{{request.user.fullname}}</h3>
          </div>
          <div class="col-4 text-right">
            <a href="{% url 'account_change_password' %}" class="btn btn-sm btn-primary">Update Password</a>
          </div>
        </div>
      </div>
      <div class="card-body">
        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% url 'users:update' %}">
          {% csrf_token %}
          <h6 class="heading-small text-muted mb-4">User information</h6>
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}