bizwallet/blog/urls.py
from django.urls import path

from .views import PostDetail, PostList, SearchPostList, post_share, tag_posts

app_name = "blogs"
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('search/', SearchPostList.as_view(), name="search"),
    path('<slug>/', PostDetail, name='detail'),
    path('<slug>/share/', post_share, name='share'),
    path('tag/<slug:tag_slug>/', tag_posts, name='posts_by_tag'),
]

bizwallet/core/urls.py
from django.urls import path

from bizwallet.core.views import email_subscribe, service_detail

app_name = "services"
urlpatterns = [
    path("<int:pk>/", view=service_detail, name="detail"),
    path("subscribe/", view=email_subscribe, name="subscribe"),
]

bizwallet/users/urls.py
from django.urls import path, re_path

from bizwallet.users.views import (  # subscribe_view,
    BankUpdateView,
    NotificationView,
    TopWalletViews,
    UpdatePhotoView,
    WithdrawalView,
    call_back_url,
    kin_creation,
    subscribe,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~dp-update/", view=UpdatePhotoView.as_view(), name="photo"),
    path("~bank-update/", view=BankUpdateView.as_view(), name="bank"),
    path("~add-kin/", view=kin_creation, name="kin"),
    path("~top-up/", view=TopWalletViews.as_view(), name="topup"),
    path("~withdraw/", view=WithdrawalView.as_view(), name="withdraw"),
    path("~subscribe/", view=subscribe, name="subscribe"),
    path("~notification/", view=NotificationView.as_view(), name="notif"),
    re_path("~payment/$", view=call_back_url, name="payment"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from __future__ import absolute_import

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from filebrowser.sites import site

from bizwallet.core.views import contact_view, home
from bizwallet.users.views import fieldworker_signup, investor_signup
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", home, name="home"),
    path("usersref=/<username>/", home, name="ref-home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "about/services/", TemplateView.as_view(template_name="pages/services.html"), name="services"
    ),
    path(
        "about/president/ayo-ogungbe/", TemplateView.as_view(template_name="pages/ceo.html"), name="ceo"
    ),
    path(
        "services/", include("bizwallet.core.urls"), name="services"
    ),
    path(
        "contact/", contact_view, name="contact"
    ),
    path("news/", include("bizwallet.blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# User URIs
urlpatterns += [
    # User management
    # Custom users registration
    path(
        "accounts/select/", TemplateView.as_view(template_name="account/signup_select.html"), name="account_select"
    ),
    path("accounts/signup/", investor_signup, name="account_signup"),
    path("accounts/signup-fieldworker/", fieldworker_signup, name="worker_signup"),
    path("users/", include("bizwallet.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
]

# Admin urls and security
urlpatterns += [
    # Django Admin, use {% url 'admin:index' %}
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("jet/", include("jet.urls", namespace="jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", namespace="jet-dashboard")),
    path("flatpage/", include("django.contrib.flatpages.urls")),
    path(settings.ADMIN_FILEBROWSER_URL, site.urls),
    # path('grappelli/', include('grappelli.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),
]

# SEO url settings
urlpatterns += [
    # Your stuff: custom urls includes go here
    path("sitemap.xml/", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
    path("tinymce/", include("tinymce.urls")),
    # Cookie consent
    # path('cookies/', include('cookie_consent.urls')),
    # Language switcher support urls for django
    path("i18n/", include("django.conf.urls.i18n")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # # DRF auth token
    # path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bizwallet/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField(required=True)
    to = forms.EmailField(required=True)
    comments = forms.CharField(required=False, widget=forms.Textarea)

bizwallet/blog/views.py
try:
    from urllib import quote_plus  # python 2
except:
    pass

try:
    from urllib.parse import quote_plus  # python 3
except:
    pass

import datetime

from category.models import Tag
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import transaction
from django.db.models import Count, F, Q, Sum
from django.http import HttpResponseForbidden, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, FormMixin, UpdateView

from .forms import EmailPostForm
from .models import Post  # , Comment

User = get_user_model()

# Create your views here.
class PostList(ListView):
    model = Post
    template_name = "blog/list.html"
    ordering = ["title", "-pub_date"]
    queryset = Post.objects.all_posts()
    context_object_name = "posts"
    allow_empty = True
    paginate_by = 5
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all()
        recent_posts = Post.objects.recent_posts()[:5]
        context["tags"] = tags
        context["recent_posts"] = recent_posts
        return context


class SearchPostList(ListView):
    model = Post
    template_name = "blog/search_list.html"
    ordering = ["title", "-pub_date"]
    context_object_name = "posts"
    allow_empty = True
    paginate_by = 5
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        return Post.objects.filter(
            Q(title__icontains=query) | 
            Q(content__icontains=query)
        ).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        request = self.request
        tags = Tag.objects.all()
        recent_posts = Post.objects.recent_posts()[:5]
        context["tags"] = tags
        context["recent_posts"] = recent_posts
        return context



def tag_posts(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag], status="published")
        print("tag object id = ", object_list)

    tags = Tag.objects.all()
    recent_posts = Post.objects.recent_posts()[:5]

    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    data = {
        'page': page,
        'posts': posts,
        'tags': tags,
        'recent_posts': recent_posts,
        'tag': tag
    }        
    return render(request, 'blog/tags.html', data)




def post_share(request, slug):
    post = get_object_or_404(Post, slug=slug, status="published")
    if not request.method == "POST":
        HttpResponseForbidden

    tags = Tag.objects.all()
    recent_posts = Post.objects.recent_posts()[:5]

    form = EmailPostForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        post_url = request.build_absolute_url(post.get_absolute_url())
        subject = f"{cd['name']} recommends you read {post.title}"
        message = f"Read {post.title} at {post_url} \n\n {cd['name']}\'s comments: {cd['comments']}"
        send_mail(
            subject,
            message,
            "info@bizwallet.com",
            [cd['to']],
            fail_silently=False
        )
        messages.success(request, f"You have successfully shared {post.title}")
        return HttpResponseRedirect(reverse_lazy('blogs:list'))
    else:
        form = EmailPostForm()

    data = {
        'tags': tags,
        'recent_posts': recent_posts,
        'post': post, 
        'form': form
    }
    
    return render(request, 'blog/share.html', data)




def PostDetail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    tags = Tag.objects.all()
    recent_posts = Post.objects.recent_posts().exclude(id=post.id)[:5]
    post_tags_ids = post.tags.values_list('id', flat=True)
    related_posts = Post.objects.all_posts().filter(tags__in=post_tags_ids).exclude(id=post.id)
    related_posts = related_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-pub_date')[:5]




    data = {
        "post": post,
        'recent_posts': recent_posts,
        'related_posts': related_posts,
        "tags": tags
    }
    return render(request, "blog/detail.html", data)

bizwallet/core/views.py
from __future__ import absolute_import

import json
import os

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import BadHeaderError, EmailMessage, send_mail, send_mass_mail
from django.http import Http404, HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from tinymce.views import render_to_image_list

from bizwallet.users.forms import TestimonyForm
from bizwallet.users.models import Testimonial

from .forms import ContactForm, EmailSubscribeForm
from .models import EmailSubscribe, Services

User = get_user_model()

devnull = open(os.devnull, "w")


def compress_whitespace(s):
    return " ".join(s.split())

def get_ip_address(request):
    """ use requestobject to fetch client machine's IP Address """
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', None)
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR', None)    ### Real IP address of client Machine
    return ip  

@cache_page(60 * 10)  # cached in 1 second.. for 15 minutes (60 sec x 15mins)
@csrf_protect
def home(request, *args, **kwargs):
    # get referrer linked to reffered using username
    username = str(kwargs.get("username"))

    ip_address = get_ip_address(request)
    print(ip_address)

   
    services = Services.objects.all().filter(active=True)
    testimonials = Testimonial.objects.filter(active=True).order_by("-created")[:5]

    try:
        user = User.objects.get(username=username)
        if user.is_field_worker:
            request.session["fieldworker_id"] = user.id
            user_ip = request.session["fieldworker_id"]
    except:
        pass



    try:
        is_cached = "geodata" in request.session
        # get user ip and get information of the user
        if not is_cached:
            response = requests.get(f"https://reallyfreegeoip.org/json/{ip_address}")
            request.session["geodata"] = response.json()

        geodata = request.session["geodata"]
        print(geodata)
        request.session["user_ip"] = geodata["ip"]
        request.session["country"] = geodata["country_name"]
        print(request.session.get("country"))
        request.session["country_code"] = geodata["country_code"]
        request.session["region_name"] = geodata["region_name"]
        request.session["city"] = geodata["city"]
    except:
        pass

    if not request.session.get("user_ip"):
        messages.info(
            request,
            _(
                "Welcome to Bizwallet Co-Operative. Please feel free to communicate any challanges with the support team."
            ),
        )

    if request.method == 'POST':
        form = TestimonyForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('home'))
            messages.success(request, "Your review has been submitted successfuly")
            send_mail("New Testimonial Submitted", "Some Just submitted a new testimonial", "no-reply@bizwallet.org", ['info@bizwallet.org'], fail_silently=False)
    else:
        form = TestimonyForm()

    return render(request, "pages/home.html", {"form":form, "is_cached": is_cached, "services": services, "testimonials": testimonials})


class ServiceListView(DetailView):
    model = Services
    template_name = 'pages/services.html'
    context_object_name = 'services'
    queryset = Services.objects.filter(active=True)

    def get_object(self, queryset=None):
        return Services.objects.get(pk=self.kwargs.get("pk"))

service_detail = ServiceListView.as_view()


def contact_view(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            html_message = render_to_string('email/support_mail.html', {'message': message, 'from_email': from_email, 'subject': subject})

            try:
                send_mail(subject, message, from_email, ['info@bizwallet.org'], html_message=html_message, fail_silently=False)
                messages.success(request, "Your Email Has been sent successfuly")
            except BadHeaderError:
                messages.error(request, "There was an error sending yout email at the moment, please try again later.")
                # return HttpResponse('Invalid Header found')
            return redirect('home')
    return render(request, 'pages/contact.html', {'form': form})



class UserEmailSubscribe(SuccessMessageMixin, CreateView):

    model = EmailSubscribe
    template_name = "snippets/footer.html"
    form_class = EmailSubscribeForm
    success_url = reverse_lazy("home")
    success_message = _("Email successfully added to our email list")

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())

email_subscribe = UserEmailSubscribe.as_view()

bizwallet/templates/snippets/css.html
{% load static compress %}


{% block css %}

<!-- Your stuff: Third-party CSS libraries go here -->
{% compress css inline %}
<!-- This file stores project-specific CSS -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/dark.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font-icons.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css" />

<link rel="stylesheet" href="{% static 'css/components/datepicker.css' %}" type="text/css" />

<link href="{% static 'css/project.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'demos/coworking/css/fonts.css' %}" type="text/css" /> <!-- Theme Font -->
<link rel="stylesheet" href="{% static 'demos/coworking/coworking.css' %}" type="text/css" /> <!-- Theme CSS -->
<link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css" />
{% endcompress %}

{% endblock %}

bizwallet/templates/snippets/dash_nav.html
{% load static i18n %}

<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars" aria-hidden="true"></i>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0" href="{% url 'home' %}">
        <img src="{% static 'images/logo@2x.png' %}" height="120" class="navbar-brand-img" alt="bizwallet logo">
      </a>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
        <!-- <li class="nav-item dropdown">
          <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{% if request.user.image %}{{object.image.url}}{% else %}{% static 'images/user.png' %}{% endif %}">
              </span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <div class=" dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome {% if request.user.is_authenticated %}{{request.user.fullname}}{% endif %}!</h6>
            </div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'users:update' %}" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-calendar-grid-58"></i>
              <span>Activity</span>
            </a>
            <a href="{% url 'contact' %}" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'account_change_password' %}" class="dropdown-item">
              <i class="ni ni-settings-gear-65"></i>
              <span>Settings</span>
            </a>
            <a href="{% url 'account_logout' %}" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>Login</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'account_select' %}" class="dropdown-item">
                <i class="ni ni-spaceship"></i>
                <span>Signup</span>
              </a>
              {% endif %}
          </div>
        </li>
      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="{% url 'home' %}">
                <img src="{% static 'images/logo@2x.png' %}" height="120">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Form -->
        <!-- Navigation -->
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
          <li class="nav-item  active ">
            <a class="nav-link  active " href="{% url 'users:detail' request.user.username %}">
              <i class="ni ni-tv-2 text-primary"></i> Dashboard
            </a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'users:update' %}">
              <i class="ni ni-single-02 text-warning"></i> User profile
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'users:kin' %}">
              <i class="ni ni-single-02 text-warning"></i> Next of Kin
            </a>
          </li>
          {% if request.user.is_verified %}
          <li class="nav-item">
            <a href="{% url 'users:withdraw' %}" class="nav-link">
              <i class="ni ni-credit-card text-danger"></i> Withdraw Funds
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'users:topup' %}" class="nav-link">
              <i class="ni ni-credit-card text-success"></i> Top-Up Wallet
            </a>
          </li>
          {% endif %}
          {% endif %}
          <li class="nav-item">
            <a class="nav-link " href="./examples/icons.html">
              <i class="ni ni-calendar-grid-58 text-yello"></i> Activities
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'contact' %}">
              <i class="ni ni-support-16 text-orange"></i> Support
            </a>
          </li>
          {% if object == request.user.is_superuser or object == request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'admin:index' %}">
              <i class="ni ni-single-02 text-yellow"></i> Backend
            </a>
          </li>
          {% endif %}
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading text-muted">Configuration</h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_change_password' %}">
                  <i class="ni ni-key-25"></i> Password Setting
                </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="/accounts/email/">
                <i class="ni ni-email-83"></i> Email Setting
            </a>
            </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:notif' %}">
              <i class="ni ni-bell-55"></i> Notification Setting
            </a>
          </li>
        </ul>
      </div>
    </div>
</nav>

bizwallet/templates/snippets/nav.html
{% load static i18n %}
{% url 'home' as home_url %}
{% url 'about' as about_url %}
<header id="header" class="border-bottom-0" data-sticky-shrink="false">
    <div id="header-wrap">
        <div class="container">
            <div class="header-row">

                <!-- Logo
                ============================================= -->
                <div id="logo">
                    <a href="{% url 'home' %}" class="standard-logo" data-sticky-logo="{% static 'images/logo-sticky 1.png' %}"><img src="{% static 'images/logo.png' %}" alt="Bizwallet Logo"></a>
                    <a href="{% url 'home' %}" class="retina-logo" data-sticky-logo="{% static 'images/logo-sticky@2x 1.png' %}"><img src="{% static 'images/logo@2x.png' %}" alt="Bizwallet Logo"></a>
                </div><!-- #logo end -->

                <div class="header-misc">
                    <a class="top-phone" href="{% if not request.user.is_authenticated %}{% url 'account_login' %}{% else %}{% url 'account_logout' %}{% endif %}"><i class="icon-lock1"></i> <span class="d-none d-md-inline-block">{% if request.user.is_authenticated %}Logout{% else %}Login{% endif %}</span></a>
                </div>
                <div class="header-misc">
                    <a class="top-phone" href="{% if not request.user.is_authenticated %}{% url 'account_select' %}{% else %}{% url 'users:detail' request.user.username %}{% endif %}"><i class="icon-users1"></i> <span class="d-none d-md-inline-block">{% if request.user.is_authenticated %}{{request.user.fullname}}{% else %}Get Started{% endif %}</span></a>
                </div>

                <div id="primary-menu-trigger">
                    <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                </div>

                <!-- Primary Navigation
                ============================================= -->
                <nav class="primary-menu">

                    <ul class="menu-container">
                        <li class="menu-item current"><a class="menu-link" href="{% url 'home' %}"><div>Home</div></a></li>
                        <li class="menu-item">
                            <a class="menu-link" href="#"><div><i class="icon-bones"></i> Bizwallet</div></a>
                            <ul class="sub-menu-container">
                                <li class="menu-item">
                                    <a class="menu-link" href="#"><div><i class="icon-stack"></i>Who We Are</div></a>
                                    <ul class="sub-menu-container">
                                        <li class="menu-item">
                                            <a class="menu-link" href="{% url 'about' %}"><div>Our Story</div></a>
                                            <li class="menu-item">
                                                <a class="menu-link" href="{% url 'services' %}"><div>Our Services</div></a>
                                            </li>
                                            <li class="menu-item">
                                                <a class="menu-link" href="{% url 'ceo' %}"><div>Our CEO</div></a>
                                            </li>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="{% url 'blogs:list' %}"><div>Blog</div></a></li>
                        <li class="menu-item"><a class="menu-link" href="{% url 'contact' %}"><div>Contact Us</div></a></li>
                    </ul>

                </nav><!-- #primary-menu end -->

            </div>
        </div>
    </div>
    <div class="header-wrap-clone"></div>
</header><!-- #header end -->